# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-28 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_sendgrid', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bouncereason',
            options={'verbose_name': 'Bounce Reason', 'verbose_name_plural': 'Bounce Reasons'},
        ),
        migrations.AlterModelOptions(
            name='bouncetype',
            options={'verbose_name': 'Bounce Type', 'verbose_name_plural': 'Bounce Types'},
        ),
        migrations.AlterModelOptions(
            name='clickurl',
            options={'verbose_name': 'Click Url', 'verbose_name_plural': 'Click Urls'},
        ),
        migrations.AlterModelOptions(
            name='deferredevent',
            options={'verbose_name': 'Deferred Event', 'verbose_name_plural': 'Deferred Events'},
        ),
        migrations.AlterModelOptions(
            name='deliverredevent',
            options={'verbose_name': 'Deliverred Event', 'verbose_name_plural': 'Deliverred Events'},
        ),
        migrations.AlterModelOptions(
            name='droppedevent',
            options={'verbose_name': 'Dropped Event', 'verbose_name_plural': 'Dropped Events'},
        ),
        migrations.AlterModelOptions(
            name='eventtype',
            options={'verbose_name': 'Event Type', 'verbose_name_plural': 'Event Types'},
        ),
    ]
